version: '2.1'
orbs:
  vercel: i-am-jeetu/vercel@x.y
jobs:
  deploy:
    executor: vercel/default
    steps:
      - checkout
      - vercel/install
      - vercel/check-authentication
      - run:
          command: >
            echo "The command above installs Vercel, the command below deploys.
            What you do inbetween is up to you!"
      - vercel/deploy
workflows:
  vercel_deploy:
    jobs:
      - deploy
